### PR TITLE
Fail CI on clippy warnings

### PR DESCRIPTION
**Pull request by dburgener**

### CODE REVIEW

**Comment by l0kod** [comment]
Could you move commit https://github.com/dburgener/cascade/pull/11/commits/df97f6c8a1f229c864e66a093cf03912330fe2e2 into #9?

**Comment by l0kod** [comment]
Well, actually squashing the commit into one of #9 would be better.

**Comment by dburgener** [comment]
> Could you move commit https://github.com/dburgener/cascade/commit/df97f6c8a1f229c864e66a093cf03912330fe2e2 into https://github.com/dburgener/cascade/pull/9?

I'm confused.  Why would that be preferred?  This is broken totally independently of #9. I just happened to notice it when posting #9.

**Comment by l0kod** [comment]
That was to avoid warning on PR updates and make sure that, from now on, all PR will make clippy happy.

**Pull request merged**
